Config.h File Reference
Configuration struct and load/block helpers for the load balancer.
#include <string>
#include <vector>
Classes
struct Config
Holds load balancer settings loaded from a config file.
Functions
bool loadConfig (const std::string &path, Config &out)
Loads configuration from a file into the given struct.
bool isIPBlocked (const Config &cfg, const std::string &ip)
Returns whether an IP address is in any blocked range in the config.
Detailed Description
Configuration struct and load/block helpers for the load balancer.
Author
Brady Nguyen
Date
February 2026
Definition in file Config.h.
Function Documentation
isIPBlocked()
bool isIPBlocked (const Config & cfg, const std::string & ip)
Returns whether an IP address is in any blocked range in the config.
Parameters
cfg Loaded configuration (blockedIPRanges used).
ip Dotted-decimal IPv4 address (e.g. "192.168.1.1").
Returns
true if ip is blocked, false otherwise.
Definition at line 103 of file Config.cpp.
Referenced by LoadBalancer::enqueueRequest(), LoadBalancer::initialize(), and LoadBalancer::runCycle().
loadConfig()
bool loadConfig (const std::string & path, Config & out)
Loads configuration from a file into the given struct.
Parameters
path Path to the config file (e.g. "config.txt").
out Config struct to fill; existing values used as defaults if key missing.
Returns
true if file was opened and parsed, false on open error (out unchanged).
Definition at line 61 of file Config.cpp.
Referenced by main().