Request.h File Reference
Request struct and random request generator for load balancer simulation.
#include "Config.h"
#include <string>
Classes
struct Request
Represents a single web request with IP addresses, processing time, and job type.
Functions
Request generateRandomRequest (const Config &cfg)
Generates a random request with random IPs, cycle count, and job type.
Detailed Description
Request struct and random request generator for load balancer simulation.
Author
Brady Nguyen
Date
February 2026
Definition in file Request.h.
Function Documentation
generateRandomRequest()
Request generateRandomRequest (const Config & cfg)
Generates a random request with random IPs, cycle count, and job type.
Parameters
cfg Config providing taskTimeMin and taskTimeMax for cycles_needed range.
Returns
A new Request with random IP_in, IP_out, cycles_needed in [taskTimeMin, taskTimeMax], and job_type ('P' or 'S').
Definition at line 31 of file Request.cpp.
Referenced by LoadBalancer::initialize(), Switch::initialize(), LoadBalancer::runCycle(), and Switch::runCycle().