Request.cpp File Reference
Implementation of random request generation.
#include "Request.h"
#include "Config.h"
#include <cstdlib>
#include <ctime>
#include <sstream>
Functions
Request generateRandomRequest (const Config &cfg)
Generates a random request with random IPs, cycle count, and job type.
Detailed Description
Implementation of random request generation.
Author
Brady Nguyen
Date
February 2026
Definition in file Request.cpp.
Function Documentation
generateRandomRequest()
Request generateRandomRequest (const Config & cfg)
Generates a random request with random IPs, cycle count, and job type.
Parameters
cfg Config providing taskTimeMin and taskTimeMax for cycles_needed range.
Returns
A new Request with random IP_in, IP_out, cycles_needed in [taskTimeMin, taskTimeMax], and job_type ('P' or 'S').
Definition at line 31 of file Request.cpp.
Referenced by LoadBalancer::initialize(), Switch::initialize(), LoadBalancer::runCycle(), and Switch::runCycle().